spring.application.name=backend

# Configuración de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_db
spring.datasource.username=inventario_user
spring.datasource.password=inventario_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará las tablas automáticamente en desarrollo basándose en nuestras entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS (frontend Angular local)
app.cors.allowed-origins=http://localhost:4200

